name: Format Python code
on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]
jobs:
  Autoyapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Auto yapf
        uses: Ryomen-Sukuna/yapf-action@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@master
        with:
          commit-message: Automated code formatting.
          committer: Ryomen-Sukuna<80420642+Ryomen-Sukuna@users.noreply.github.com>
          title: Automated code formatting.
          body: This is an automated code formatting pull request.
          labels: Code Formatting
          reviewers: Ryomen-Sukuna
          branch: autofix
